### ISSUE TITLE
Missing link on "Continuous Integration" page

### ISSUE THREAD

**Issue by anthony-chu** [liferay/liferay-learn#40]
**Describe the bug**
On the "Continuous Integration" page, the text "Using the Jenkinsfile" is missing a hyperlink reference

**To Reproduce**
1. Navigate to /dxp-cloud-latest/html/platform-services/continuous-integration.html
1. View "Using the Jenkinsfile" text under "Additional Information"

**Expected behavior**
"Using the Jenkinsfile" text has a hyperlink reference to a page

**Actual behavior**
Text has no hyperlink reference

**Comment by justinchoi001** [comment]
Removing placeholder.

**Comment by justinchoi001** [comment]
@jrhoun , please close. Fixed in https://github.com/jrhoun/liferay-learn/pull/29

**Comment by jrhoun** [comment]
@anthony-chu - we removed the placeholder but still have a backlog item to write this article.
